version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_db_password
      MYSQL_DATABASE: printvista
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  user-service:
    build: .
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=3011
      - JWT_SECRET=your_jwt_secret
      - ALLOWED_ORIGINS=*
      - DB_DIALECT=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=printvista
      - DB_USER=root
      - DB_PASS=your_db_password
    ports:
      - "3011:3011"
    env_file:
      - .env.development
volumes:
  db_data:
